// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';
import '../../utils/podDb/poddb_handler.dart';

export 'package:objectbox/objectbox.dart';

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3428807048063053727),
    name: 'Docket',
    lastPropertyId: const obx_int.IdUid(9, 6538002801567773001),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4257787385389240912),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1650999329378668320),
        name: 'dockNo',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 2890342879237524881),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1197802415781922596),
        name: 'dockDt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 867044325694114951),
        name: 'tripSheetNo',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8658208159730185547),
        name: 'podImagePaths',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4685961544342436417),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3030893445808452082),
        name: 'buttonName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8295068708360376669),
        name: 'apiStatusIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6538002801567773001),
        name: 'loading',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6087636667163249931),
    name: 'StringEntity',
    lastPropertyId: const obx_int.IdUid(2, 3648032499025554649),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2261828453836316281),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3648032499025554649),
        name: 'value',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 6087636667163249931),
    lastIndexId: const obx_int.IdUid(1, 2890342879237524881),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1, generatorVersion: obx_int.GeneratorVersion.none,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Docket: obx_int.EntityDefinition<Docket>(
      model: _entities[0],
      toOneRelations: (Docket object) => [],
      toManyRelations: (Docket object) => {},
      getId: (Docket object) => object.id,
      setId: (Docket object, int id) {
        object.id = id;
      },
      objectToFB: (Docket object, fb.Builder fbb) {
        final dockNoOffset = fbb.writeString(object.dockNo);
        final dockDtOffset = fbb.writeString(object.dockDt);
        final tripSheetNoOffset = fbb.writeString(object.tripSheetNo);
        final podImagePathsOffset = fbb.writeList(
          object.podImagePaths.map(fbb.writeString).toList(growable: false),
        );
        final statusOffset = fbb.writeString(object.status);
        final buttonNameOffset = fbb.writeString(object.buttonName);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, dockNoOffset);
        fbb.addOffset(2, dockDtOffset);
        fbb.addOffset(3, tripSheetNoOffset);
        fbb.addOffset(4, podImagePathsOffset);
        fbb.addOffset(5, statusOffset);
        fbb.addOffset(6, buttonNameOffset);
        fbb.addInt64(7, object.apiStatusIndex);
        fbb.addBool(8, object.loading);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dockNoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final dockDtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final tripSheetNoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final podImagePathsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 12, []);
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final buttonNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final apiStatusIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final loadingParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final object = Docket(
          dockNo: dockNoParam,
          dockDt: dockDtParam,
          tripSheetNo: tripSheetNoParam,
          podImagePaths: podImagePathsParam,
          status: statusParam,
          buttonName: buttonNameParam,
          apiStatusIndex: apiStatusIndexParam,
          loading: loadingParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    StringEntity: obx_int.EntityDefinition<StringEntity>(
      model: _entities[1],
      toOneRelations: (StringEntity object) => [],
      toManyRelations: (StringEntity object) => {},
      getId: (StringEntity object) => object.id,
      setId: (StringEntity object, int id) {
        object.id = id;
      },
      objectToFB: (StringEntity object, fb.Builder fbb) {
        final valueOffset = fbb.writeString(object.value);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, valueOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final valueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = StringEntity(value: valueParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Docket] entity fields to define ObjectBox queries.
class Docket_ {
  /// See [Docket.id].
  static final id = obx.QueryIntegerProperty<Docket>(
    _entities[0].properties[0],
  );

  /// See [Docket.dockNo].
  static final dockNo = obx.QueryStringProperty<Docket>(
    _entities[0].properties[1],
  );

  /// See [Docket.dockDt].
  static final dockDt = obx.QueryStringProperty<Docket>(
    _entities[0].properties[2],
  );

  /// See [Docket.tripSheetNo].
  static final tripSheetNo = obx.QueryStringProperty<Docket>(
    _entities[0].properties[3],
  );

  /// See [Docket.podImagePaths].
  static final podImagePaths = obx.QueryStringVectorProperty<Docket>(
    _entities[0].properties[4],
  );

  /// See [Docket.status].
  static final status = obx.QueryStringProperty<Docket>(
    _entities[0].properties[5],
  );

  /// See [Docket.buttonName].
  static final buttonName = obx.QueryStringProperty<Docket>(
    _entities[0].properties[6],
  );

  /// See [Docket.apiStatusIndex].
  static final apiStatusIndex = obx.QueryIntegerProperty<Docket>(
    _entities[0].properties[7],
  );

  /// See [Docket.loading].
  static final loading = obx.QueryBooleanProperty<Docket>(
    _entities[0].properties[8],
  );
}

/// [StringEntity] entity fields to define ObjectBox queries.
class StringEntity_ {
  /// See [StringEntity.id].
  static final id = obx.QueryIntegerProperty<StringEntity>(
    _entities[1].properties[0],
  );

  /// See [StringEntity.value].
  static final value = obx.QueryStringProperty<StringEntity>(
    _entities[1].properties[1],
  );
}
